### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by MaSchm1983** [BTNeandertha1/BTDiablo#24]
Hey BT,

I tried parts of your very nice mod and found some minor bugs.
- the inventorys GridX in global/excel/inventory.txt is 11 but the sprites seem to be made for 10 GridX ==> results in a blue bar on the right hand side. 
- The skills "Charged strike", "Plaque javalin" and "Penetrate" are nameless :-) or at least they are called "an evil force" in the tool tip, which basically means, the game doesn't find the right name. But I have no clue in which file the names are stored. 

Just a few minor things :-)

Cheers

**Comment by BTNeandertha1** [comment]
Hey thanks for bringing this to my attention!

1. The blue bar on the right of the inventory is on purpose those are the
-effects of the game they are charms. Unfortunately, the other way I was
trying to do stuff like this wouldn't work.

2. This was a bug we had quite some time ago and is now fixed in current
day patches.

Cheers
