### ISSUE TITLE
Lower Kurast full of invisible mobs

### ISSUE THREAD

**Issue by Mastadon85** [BTNeandertha1/BTDiablo#27]
Invisible suicide monsters in Kurast. This makes it very annoying as a melee character navigating through Kurast as you run into these invisible mobs, then they knock you back as they explode... is this intentional? I think they should be removed...

**Comment by WolfieeifloW** [comment]
This is intentional.

**Comment by Sveet** [comment]
Thank you for clarifying that this is an intentional feature.

My feedback is that this is an anti-fun game mechanic. Players should not be attacked/killed without any opportunity to react. There are other ways to discourage LK farming, if that is the intention.

For others reading, you can modify line 81 of your [btdiablo.mpq/data/global/excel/levels.txt](https://github.com/BTNeandertha1/BTDiablo/blob/main/btdiablo.mpq/data/global/excel/levels.txt#L81). Change the NM and Hell minions to match the Normal ones. `suicideminion6	bonefetish6	bonefetish6` -> `baboon4	sandleaper4	zealot2` Mind the tab characters. Save and reopen your game.
