### ISSUE TITLE
Can't connect to battlenet games with mod?

### ISSUE THREAD

**Issue by Pietroma** [BTNeandertha1/BTDiablo#38]
I seem to not be able to play on battlenet when I have the mod loading in the battlenet launcher. When I delete the additional command line arguments, I can conect to battlenet again. Is this how it works or did i do something wrong?

**Comment by mapron** [comment]
You can't use mods (any) when connecting to battlenet, that's it :D  all modding in D2R is strictly for offline play.

**Comment by Pietroma** [comment]
Okay! I for some reason thought the mod was only affecting offline, not
online. Idk why my brain was thinking that way lol. It makes sense now, my
bad.

**Comment by mapron** [comment]
mod is affecting offline, but mod manager in  D2R is weird. Long time ago in 2.4 or before you could load offline mod and go online and play unmodded. Now they changed it, so if you play modded shortcut you no longer can go online probably because it is harder to switch from one loaded file data to another (D2R reads game file at exe launch, in contrast to LoD).

**Comment by Pietroma** [comment]
Thanks for explaining to me man, I’m excited to play the mood either way!
